[build]
builder = "docker"
dockerfilePath = "Dockerfile"
# Information for the wheelhouse: Explicitly using Dockerfile to avoid Nixpacks confusion.

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
maxRestartRetries = 10
